### ISSUE TITLE
[JOSS REVIEW] - Documentation missing

### ISSUE THREAD

**Issue by trallard** [AustinNar/tabulog#1]
There is `docs` directory  but I could not find a way to access the docs for the package. In brief the docs should at least cover the following for the review:
- Installation instructions
- Example usage
- Functionality

**Comment by austinrwarner** [comment]
@trallard please see my changes in:
- [README.md](https://github.com/AustinNar/tabulog/blob/master/README.md)
- [docs/README.md](https://github.com/AustinNar/tabulog/blob/master/docs/README.md)
