### ISSUE TITLE
[JOSS REVIEW] - contributing guidelines

### ISSUE THREAD

**Issue by trallard** [AustinNar/tabulog#2]
In order to proceed with the JOSS review we require that you add contributing guidelines to the repo

**Comment by austinrwarner** [comment]
@trallard please see my changes in:
- [README.md](https://github.com/AustinNar/tabulog/blob/master/README.md)
- [CONTRIBUTING.md](https://github.com/AustinNar/tabulog/blob/master/CONTRIBUTING.md)
